### ISSUE TITLE
rails 5.2, anyone tested it with rails 5.2?

### ISSUE THREAD

**Issue by ghost** [itmLABS/exceptiontrap#1]
I tried to run it on heroku and it seems to not be passing the boot:

```

2018-05-29T15:23:30.361956+00:00 heroku[web.1]: Starting process with command `bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}`

2018-05-29T15:23:32.931965+00:00 app[web.1]: [4] Puma starting in cluster mode...
2018-05-29T15:23:32.931998+00:00 app[web.1]: [4] * Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
2018-05-29T15:23:32.932001+00:00 app[web.1]: [4] * Min threads: 5, max threads: 5
2018-05-29T15:23:32.932007+00:00 app[web.1]: [4] * Environment: production
2018-05-29T15:23:32.932008+00:00 app[web.1]: [4] * Process workers: 2
2018-05-29T15:23:32.932010+00:00 app[web.1]: [4] * Preloading application


2018-05-29T15:23:36.860236+00:00 app[web.1]: [4] ! Unable to load application: RuntimeError: No such middleware to insert after: "ActionDispatch::ShowExceptions"
2018-05-29T15:23:36.860520+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.5.0/bin/puma)
2018-05-29T15:23:36.860605+00:00 app[web.1]: RuntimeError: No such middleware to insert after: "ActionDispatch::ShowExceptions"
2018-05-29T15:23:36.860608+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/stack.rb:108:in `assert_index'
2018-05-29T15:23:36.860610+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/stack.rb:82:in `insert_after'
2018-05-29T15:23:36.860612+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/configuration.rb:71:in `block in merge_into'
2018-05-29T15:23:36.860614+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/configuration.rb:70:in `each'
2018-05-29T15:23:36.860616+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/configuration.rb:70:in `merge_into'
2018-05-29T15:23:36.860617+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:509:in `block in app'
2018-05-29T15:23:36.860619+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:506:in `synchronize'
2018-05-29T15:23:36.860639+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:506:in `app'
2018-05-29T15:23:36.860641+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
2018-05-29T15:23:36.860643+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
2018-05-29T15:23:36.860644+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
2018-05-29T15:23:36.860646+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
2018-05-29T15:23:36.860648+00:00 app[web.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
2018-05-29T15:23:36.860649+00:00 app[web.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
2018-05-29T15:23:36.860655+00:00 app[web.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
2018-05-29T15:23:36.860657+00:00 app[web.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
2018-05-29T15:23:36.860660+00:00 app[web.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each'
2018-05-29T15:23:36.860662+00:00 app[web.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `call'
2018-05-29T15:23:36.860664+00:00 app[web.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
2018-05-29T15:23:36.860665+00:00 app[web.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
2018-05-29T15:23:36.860667+00:00 app[web.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
2018-05-29T15:23:36.860668+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
2018-05-29T15:23:36.860670+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
2018-05-29T15:23:36.860671+00:00 app[web.1]: /app/config/environment.rb:5:in `<top (required)>'
2018-05-29T15:23:36.860673+00:00 app[web.1]: config.ru:3:in `require_relative'
2018-05-29T15:23:36.860675+00:00 app[web.1]: config.ru:3:in `block in <main>'
2018-05-29T15:23:36.860677+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
2018-05-29T15:23:36.860678+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
2018-05-29T15:23:36.860680+00:00 app[web.1]: config.ru:in `new'
2018-05-29T15:23:36.860682+00:00 app[web.1]: config.ru:in `<main>'
2018-05-29T15:23:36.860683+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
2018-05-29T15:23:36.860685+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
2018-05-29T15:23:36.860686+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
2018-05-29T15:23:36.860688+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/puma-3.11.4/lib/puma/configuration.rb:318:in `load_rackup'
2018-05-29T15:23:36.860690+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/puma-3.11.4/lib/puma/configuration.rb:243:in `app'
2018-05-29T15:23:36.860691+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/puma-3.11.4/lib/puma/runner.rb:138:in `load_and_bind'
2018-05-29T15:23:36.860693+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/puma-3.11.4/lib/puma/cluster.rb:397:in `run'
2018-05-29T15:23:36.860694+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/puma-3.11.4/lib/puma/launcher.rb:184:in `run'
2018-05-29T15:23:36.860696+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/puma-3.11.4/lib/puma/cli.rb:78:in `run'
2018-05-29T15:23:36.860697+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/puma-3.11.4/bin/puma:10:in `<top (required)>'
2018-05-29T15:23:36.860699+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/bin/puma:23:in `load'
2018-05-29T15:23:36.860701+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/bin/puma:23:in `<top (required)>'
2018-05-29T15:23:37.078688+00:00 heroku[web.1]: Process exited with status 1
2018-05-29T15:23:37.099279+00:00 heroku[web.1]: State changed from starting to crashed


```

**Comment by tbuehl** [comment]
@sayduck-daniel This has been fixed with version 1.1.1. Thanks for bringing it up!
